# -*- coding: utf-8 -*-
"""CO2_Emission_Case_Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFH6E657Y0LyDU_uSOXtS1pBHL00XWix
"""

import pandas as pd

df = pd.read_csv('https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/158/208/original/CO2_Emissions.csv?1760012266')

df.info()

df.isnull().sum()

(df.isnull().sum())/len(df.index)*100

"""#data set is clean, no null values, no need to remove any rows containing null values using pd.isnull or np.isnan"""

df.info()

df.head()

"""#from above result, CO2 Emissions(g/km) is a target variable(depenedent variable) and rest are independent variables which will help in making interpretations

#Q1: Begin by familiarizing yourself with the dataset. Identify what kind of information is captured about vehicles and how these variables might influence CO₂ emissions.
"""

df.columns

target = 'CO2 Emissions(g/km)'

import numpy as np

independent_variables = np.setdiff1d(df.columns, target)
independent_variables

"""#Q2 Examine the dataset for any inconsistencies, missing entries, or data quality issues. Consider what preprocessing steps may be necessary to make the dataset ready for meaningful analysis.

#To start with, Model column has space separated values, which makes it difficult to identify unique rows, so retain strings before space
"""

#To start with, Model column has space separated values, which makes it difficult to identify unique rows, so retain strings before space

df['Model'] = df['Model'].apply(lambda x:x.split()[0])
df['Model']

df['Model'].value_counts()

"""# check for any null or missing values

"""

df.isnull().sum()/len(df.index)*100

"""# No null or missing values, Columns like Make, Model, Vehicle CLass may not contribute to interpretation of Co2 emissions so dropping those colums"""

master = df.drop(['Make', 'Model', 'Vehicle Class'], axis=1)

"""#Q3 Study the relationships between various vehicle features and CO₂ emissions. Which attributes appear to have stronger influence on emission levels? Use suitable methods to support your reasoning."""

master['CO2 Emissions(g/km)'].describe()

#correlation matrix helps in determining which feature are most important for making interpretations on co2 emission

master.head()

#since Fuel Type and Transmission are not numeric attributes, we can use one hot encoding to convert them

categorical_cols = ['Transmission', 'Fuel Type']

master_encoded = pd.get_dummies(master, columns=categorical_cols, dtype=int, drop_first=True)
master_encoded.head()

"""#correlation matrix"""

corr_matrix = master_encoded.corr()

corr_matrix

co2_corr = corr_matrix['CO2 Emissions(g/km)'].sort_values(ascending=False)

co2_corr

print("Top correlations with CO2 Emissions:\n")
print(co2_corr.head(15))

"""#Fuel Consumption City and Fuel Consumption Comb (L/100 km) are top 2 columns that are most related to C02 Emissions(g/km) i.e. As one increases, the other increases

#Q4: Create visual summaries that reveal how emission levels change with respect to different numerical variables in the dataset. Focus on uncovering patterns or trends that might not be immediately visible.
"""

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

# --- Homoscedastic data ---
np.random.seed(42)
x1 = np.linspace(0, 10, 100)
y1 = 3*x1 + np.random.normal(0, 2, 100)  # constant variance

# --- Heteroscedastic data ---
x2 = np.linspace(0, 10, 100)
y2 = 3*x2 + np.random.normal(0, 0.5*x2, 100)  # variance increases with x

# --- Fit models ---
model1 = sm.OLS(y1, sm.add_constant(x1)).fit()
model2 = sm.OLS(y2, sm.add_constant(x2)).fit()

# --- Get fitted values and residuals ---
fitted1, resid1 = model1.fittedvalues, model1.resid
fitted2, resid2 = model2.fittedvalues, model2.resid

# --- Plot ---
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.scatter(fitted1, resid1, color='green', alpha=0.7)
plt.axhline(y=0, color='black', linestyle='--')
plt.title('✅ Homoscedasticity\n(Constant variance)')
plt.xlabel('Fitted values')
plt.ylabel('Residuals')

plt.subplot(1,2,2)
plt.scatter(fitted2, resid2, color='red', alpha=0.7)
plt.axhline(y=0, color='black', linestyle='--')
plt.title('⚠️ Heteroscedasticity\n(Funnel shape)')
plt.xlabel('Fitted values')
plt.ylabel('Residuals')

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
all_columns = master_encoded.columns

for i in all_columns:
  sns.scatterplot(x=i, y='CO2 Emissions(g/km)', data=master_encoded, alpha=0.7)
  plt.title(f'CO₂ Emissions vs {i}')
  plt.show()

"""#Q5 Compare emission levels across different vehicle types or fuel categories. Identify any clear distinctions or surprising findings that emerge."""

df.columns

df['CO2 Emissions(g/km)'].describe()

"""# choose mean as a aggregate function, each each vehicle class + fuel type, you get average so that we can check which combination has highest and lowest emissions"""

df.groupby(['Vehicle Class', 'Fuel Type'])['CO2 Emissions(g/km)'].mean().sort_values(ascending=True)

"""# for VAN - PASSENGER with Fuel X, CO2 emission is highest
# for SUBCOMPACT with Fuel D, C02 emission is lowest
"""

df.groupby(['Vehicle Class'])['CO2 Emissions(g/km)'].mean().sort_values()

df.groupby(['Fuel Type'])['CO2 Emissions(g/km)'].mean().sort_values()

"""# Above 2 results show that Fuel Type does not have much impact on CO 2 emissions as max and min values are approx closer,
# But vehicle type does show much impact as the max and min values range from 200 to 397 which is a huge difference when compared to 213 and 275

#Q6 Observe if there are any vehicles that produce unusually high or low emissions compared to others with similar characteristics. Reflect on what could explain such deviations.

# To know how far a point is from mean(), we compute z-score, z-score is computed by xi - x.mean()/x.std()
# With this you get to know how far a particlar point is from mean
# Then rows whose z-score > 2 means they are 2 std deviations above mean() and all rows with z-score < -2 means they are 2 std deviations below mean(), and hence can be considered as outliers

# we need to find all those rows which ahev z-score > 2 and < - 2
"""

df['CO2_zscore'] = df.groupby(['Vehicle Class', 'Fuel Type'])['CO2 Emissions(g/km)'] \
                     .transform(lambda x: (x - x.mean()) / x.std())

# Flag unusual vehicles
unusual_high = df[df['CO2_zscore'] > 2]   # significantly above average
unusual_low = df[df['CO2_zscore'] < -2]   # significantly below average

print(f"High emission outliers: {len(unusual_high)}")
print(f"Low emission outliers: {len(unusual_low)}")

unusual_high[['Make','Model','Vehicle Class','Fuel Type','Engine Size(L)','CO2 Emissions(g/km)','CO2_zscore']].head()

"""# Common conclusion which can be derived is that all vehicles with fuel type Z and engine size in 5.9-6 L size range have high co2 emissions"""

unusual_low[['Make','Model','Vehicle Class','Fuel Type','Engine Size(L)','CO2 Emissions(g/km)','CO2_zscore']].head()

"""# Common conclusion which can be derived is that all vehicles with fuel type X and engine size in 1.8-2.5 L size range have low co2 emissions

#Q 7 Prepare the dataset for model building by ensuring that numerical and categorical features are appropriately represented. Consider any transformations or encodings that may improve interpretability.
"""

master_encoded.info()

master_encoded.isnull().sum()/len(master_encoded.index)*100

"""# All are numerical attributes and there are no Null values

#Checking if all colums are in same range if not Normalizaling using StandardScaler or MinMaxSaler is required
"""

master_encoded.head(5)

"""# Since we have performed one-hot encoding of non-numeric attributes fuel type and transmission, which has converted them into 0 and 1, and other columns are different range, we may have to perform StandardScaler"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_cols = master_encoded.columns
master_encoded[numerical_cols] = scaler.fit_transform(master_encoded[numerical_cols])

master_encoded

corr = master_encoded.corr()

corr['CO2 Emissions(g/km)'].sort_values(ascending=False)

corr

"""#Q8 Develop a simple, interpretable model to estimate CO₂ emissions using relevant features from the dataset. Summarize how the model captures the relationship between vehicle characteristics and emissions."""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

Y = master_encoded['CO2 Emissions(g/km)']
X = master_encoded.drop(['CO2 Emissions(g/km)'], axis=1)

X.shape

Y.shape

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

x_train.shape

y_train.shape

x_test.shape

y_test.shape

lm = LinearRegression()
lm.fit(x_train, y_train)

y_pred = lm.predict(x_test)

from sklearn.metrics import r2_score
lm_r2 = r2_score(y_test, y_pred)
print("R-squared:", lm_r2)

VIF = (1/(1-lm_r2))
print("VIF:", VIF)

from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

X = master_encoded.drop(['CO2 Emissions(g/km)'], axis=1)

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                   for i in range(X.shape[1])]

print(vif_data.sort_values(by="VIF", ascending=False).head(10))

"""#suggests there is multicollinearity, so find if there indepenedent variables that highly co- related

#Q9 Assess how well the model performs in estimating emissions. Reflect on the meaning of the performance metrics and what they indicate about model reliability.
#Q10 Based on the analysis and model findings, summarize which factors most strongly influence CO₂ emissions and suggest how such insights could support emission reduction efforts.
"""

master_encoded_without_co2 = master_encoded.drop(['CO2 Emissions(g/km)'], axis=1)
d = {}
for i in master_encoded_without_co2.columns:
  X = master_encoded_without_co2.drop(i, axis=1)
  Y = master_encoded_without_co2[i]
  x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
  lm = LinearRegression()
  lm.fit(x_train, y_train)
  y_pred = lm.predict(x_test)
  lm_r2 = r2_score(y_test, y_pred)
  #print(i)
  #print(lm_r2)
  d[i] = lm_r2
for i in d:
  if d[i] > 0.95:
    print(f"{i} {d[i]}")

"""# Drop each indepenedent variable, and compute it's accuracy score with rest independent variables

# This will tell which attribute will have multicollineariry with other independent variables
"""

corr = master_encoded_without_co2.corr().abs()
high_corr_pairs = corr.unstack().sort_values(ascending=False)
print(high_corr_pairs[high_corr_pairs < 1].head(10))

"""# Drop columns which have same R2 values"""

new_master = master_encoded.drop(['Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Engine Size(L)', 'Fuel Consumption City (L/100 km)', 'Transmission_A6', 'Transmission_AS6', 'Transmission_A8', 'Transmission_M6'], axis=1)
Y = new_master['CO2 Emissions(g/km)']
X = new_master.drop(['CO2 Emissions(g/km)'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
lm = LinearRegression()
lm.fit(x_train, y_train)

print(X.columns)
print(lm.coef_)
print(lm.intercept_)
y_pred = lm.predict(x_test)
lm_r2 = r2_score(y_test, y_pred)
print("R-squared:", lm_r2 )

VIF = (1/(1-lm_r2))
print("VIF:", VIF)

"""#VIF reduced from 103 to 13 which means collinearity is significantly reduced"""

from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

X = df[['Engine Size(L)', 'Fuel Consumption City (L/100 km)',
        'Fuel Consumption Hwy (L/100 km)', 'Transmission', 'Fuel Type', 'Vehicle Class']]

# One-hot encode if needed
X = pd.get_dummies(X, drop_first=True, dtype=int)

vif = pd.DataFrame()
vif["Feature"] = X.columns
vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

print(vif.sort_values(by="VIF", ascending=False))

"""Model Performance Assessment (Q9)
The linear regression model achieved an R-squared score of 0.9249 after addressing multicollinearity.

R-squared: An R-squared value of 0.9249 indicates that approximately 92.5% of the variance in CO₂ emissions can be explained by the independent variables included in the model. This is a high R-squared value, suggesting that the model fits the data well and is reliable in predicting CO₂ emissions based on the selected features.

VIF: The Variance Inflation Factor (VIF) was reduced from over 100 to around 13 after removing highly correlated features. A lower VIF indicates less multicollinearity among the independent variables, which improves the stability and interpretability of the model coefficients.

Overall, the model performs very well in estimating CO₂ emissions, and the reduction in VIF suggests that the chosen features are not excessively correlated, leading to more reliable coefficient estimates.

Gemini
Factors Influencing CO₂ Emissions and Emission Reduction Suggestions (Q10)
Based on the correlation analysis and the linear regression model, the factors that most strongly influence CO₂ emissions are:

Fuel Consumption: Both city and highway fuel consumption (L/100 km) have a very strong positive correlation with CO₂ emissions. This is expected, as burning more fuel directly leads to higher CO₂ output. Fuel Consumption Comb (mpg) has a strong negative correlation, meaning higher MPG (better fuel efficiency) results in lower CO2 emissions.
Engine Size (L) and Cylinders: These factors are highly correlated with each other and show a strong positive correlation with CO₂ emissions. Larger engines and more cylinders generally consume more fuel, leading to higher emissions.
Fuel Type: While not as strong as fuel consumption or engine characteristics, the fuel type also influences emissions. Fuel Type Z (likely premium gasoline) shows a positive correlation, while Fuel Type X (likely regular gasoline) shows a negative correlation with CO₂ emissions. This suggests that the composition and energy density of the fuel play a role.
Transmission: Some transmission types (e.g., Automatic 6-speed, Automatic 8-speed) show moderate positive correlations with CO₂ emissions, while others (e.g., Manual 5-speed, Manual 6-speed) show negative correlations. This could be due to differences in efficiency and how the transmission manages engine power and fuel delivery.
Vehicle Class: As observed in the grouped analysis, vehicle class has a significant impact on CO2 emissions, with larger vehicles like vans and standard SUVs generally having higher emissions compared to smaller vehicles like compact cars and small station wagons.
Suggestions for Emission Reduction Efforts:

Promote Fuel Efficiency: Encouraging the production and adoption of vehicles with higher fuel efficiency (lower L/100 km and higher mpg) is crucial. This can be achieved through stricter fuel economy standards, incentives for purchasing fuel-efficient vehicles, and public awareness campaigns.
Downsize Engines: Promoting smaller engine sizes and fewer cylinders can directly contribute to lower emissions, especially for vehicles where performance is not a primary concern.
Optimize Transmission Technology: Further research and development in transmission technologies can lead to more efficient power transfer and reduced fuel consumption.
Shift to Lower-Emission Fuel Types: While the impact of fuel type is less significant than other factors, promoting the use of fuels with lower carbon content or alternative fuels can contribute to emission reduction.
Encourage Smaller Vehicle Classes: Promoting the use of smaller and lighter vehicle classes, especially for urban commuting, can significantly reduce overall emissions.
Invest in Alternative Powertrains: The analysis focuses on traditional internal combustion engines. Accelerating the transition to electric vehicles, hydrogen fuel cell vehicles, and other zero-emission technologies is essential for long-term emission reduction goals.
Address Outliers: Investigating the "unusual high" emission vehicles identified in the analysis can help identify specific models or technologies that are contributing disproportionately to emissions and require targeted interventions.

"""
























































